services:
  app:
    image: online-store:local
    container_name: ps-app
    depends_on:
      - postgresql
    networks:
      - ps
    ports:
      - "8080:8080"
  postgresql:
    image: postgres:15-alpine
    container_name: ps-psql
    environment:
      - POSTGRES_DB=online-store-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ertyu55555
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_description:/docker-entrypoint-initdb.d
    networks:
      - ps
networks:
  ps: